import { Listing, ListingCategory } from './types';

export const EXPANDED_MOCK_LISTINGS: Listing[] = [
  // JOBS
  {
    id: 'j1',
    user_id: 'u1',
    category: ListingCategory.JOB,
    title: 'Senior Full Stack Engineer',
    description: 'Lead our engineering team in building next-gen fintech solutions. Expertise in React and Node.js required.',
    price: 55000,
    location: 'Bole, Addis Ababa',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { company: 'EthioTech Solutions', type: 'Full-time', salary_period: 'Monthly', industry: 'Technology' },
    created_at: new Date().toISOString(),
  },
  {
    id: 'j2',
    user_id: 'u2',
    category: ListingCategory.JOB,
    title: 'Registered Nurse (ICU)',
    description: 'Join our dedicated healthcare team. Night shifts available with competitive benefits.',
    price: 18000,
    location: 'Kazanchis, Addis Ababa',
    images: ['https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { company: 'Hayat Hospital', type: 'Full-time', salary_period: 'Monthly', industry: 'Healthcare' },
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'j3',
    user_id: 'u3',
    category: ListingCategory.JOB,
    title: 'Graphic Designer',
    description: 'Creative designer needed for social media campaigns and brand identity projects.',
    price: 12000,
    location: 'Remote',
    images: ['https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { company: 'Creative Peak', type: 'Contract', salary_period: 'Monthly', industry: 'Technology' },
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'j4',
    user_id: 'u4',
    category: ListingCategory.JOB,
    title: 'Senior Accountant',
    description: 'Handle monthly financial reporting and tax compliance for a growing manufacturing firm.',
    price: 22000,
    location: 'Adama, Ethiopia',
    images: ['https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { company: 'Horizon Manufacturing', type: 'Full-time', salary_period: 'Monthly', industry: 'Finance' },
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },

  // TENDERS
  {
    id: 't1',
    user_id: 'u5',
    category: ListingCategory.TENDER,
    title: 'Solar Panel Supply & Installation',
    description: 'Supply of 500kW solar panels for regional irrigation projects.',
    price: 4500000,
    location: 'Bahir Dar, Ethiopia',
    images: ['https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { organization: 'Ministry of Water & Energy', deadline: '2024-06-30', sector: 'Supply' },
    created_at: new Date(Date.now() - 1200000).toISOString(),
  },
  {
    id: 't2',
    user_id: 'u6',
    category: ListingCategory.TENDER,
    title: 'IT Infrastructure Upgrade',
    description: 'Modernizing data center and networking capabilities for federal offices.',
    price: 8900000,
    location: 'Addis Ababa',
    images: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc51?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { organization: 'INSA Ethiopia', deadline: '2024-07-15', sector: 'IT Services' },
    created_at: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 't3',
    user_id: 'u7',
    category: ListingCategory.TENDER,
    title: 'Fertilizer Distribution Service',
    description: 'Logistics and distribution of agricultural fertilizer to local unions.',
    price: 1250000,
    location: 'Oromia Region',
    images: ['https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { organization: 'Agri-Cooperative Union', deadline: '2024-05-10', sector: 'Agriculture' },
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },

  // PROPERTIES
  {
    id: 'p1',
    user_id: 'u8',
    category: ListingCategory.PROPERTY,
    title: 'Luxury Villa in Summit',
    description: 'Spacious G+2 villa with private garden, modern kitchen, and security system.',
    price: 45000000,
    location: 'Summit, Addis Ababa',
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { bedrooms: '4+', bathrooms: 4, area: '500sqm', listing_type: 'Sale', type: 'Villa' },
    created_at: new Date().toISOString(),
  },
  {
    id: 'p2',
    user_id: 'u9',
    category: ListingCategory.PROPERTY,
    title: 'Modern Studio Apartment',
    description: 'Fully furnished studio in a prime location. Perfect for professionals.',
    price: 18000,
    location: 'Kazanchis, Addis Ababa',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { bedrooms: 'Studio', bathrooms: 1, area: '45sqm', listing_type: 'Rent', type: 'Studio' },
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'p3',
    user_id: 'u10',
    category: ListingCategory.PROPERTY,
    title: 'Commercial Office Space',
    description: '300sqm open-plan office on the 5th floor of a brand new business center.',
    price: 120000,
    location: 'Bole, Addis Ababa',
    images: ['https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { bedrooms: '0', bathrooms: 2, area: '300sqm', listing_type: 'Rent', type: 'Office' },
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'p4',
    user_id: 'u11',
    category: ListingCategory.PROPERTY,
    title: 'Prime Land for Development',
    description: '1000sqm plot ideal for apartment or commercial building construction.',
    price: 120000000,
    location: 'Lebu, Addis Ababa',
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { bedrooms: 'N/A', area: '1000sqm', listing_type: 'Sale', type: 'Land' },
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },

  // VEHICLES
  {
    id: 'v1',
    user_id: 'u12',
    category: ListingCategory.VEHICLE,
    title: '2022 Hyundai Tucson',
    description: 'Excellent condition, low mileage, panoramic sunroof, top specs.',
    price: 6800000,
    location: 'Addis Ababa',
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { make: 'Hyundai', model: 'Tucson', year: '2022', fuel: 'Petrol', listing_type: 'Sale', body_type: 'SUV' },
    created_at: new Date().toISOString(),
  },
  {
    id: 'v2',
    user_id: 'u13',
    category: ListingCategory.VEHICLE,
    title: '2024 Suzuki Dzire',
    description: 'Brand new, zero mileage. Fuel efficient and reliable city car.',
    price: 2400000,
    location: 'Addis Ababa',
    images: ['https://images.unsplash.com/photo-1541443131876-44b03de101c5?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { make: 'Suzuki', model: 'Dzire', year: '2024', fuel: 'Petrol', listing_type: 'Sale', body_type: 'Sedan' },
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'v3',
    user_id: 'u14',
    category: ListingCategory.VEHICLE,
    title: 'Mercedes-Benz E300 (Electric)',
    description: 'Luxury electric sedan with high range and advanced safety features.',
    price: 14500000,
    location: 'Old Airport, Addis Ababa',
    images: ['https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { make: 'Mercedes', model: 'E300', year: '2023', fuel: 'Electric', listing_type: 'Sale', body_type: 'Sedan' },
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'v4',
    user_id: 'u15',
    category: ListingCategory.VEHICLE,
    title: 'Toyota Hilux Double Cabin',
    description: 'Strong pickup for tough terrains. 4x4, diesel engine.',
    price: 9200000,
    location: 'Hawassa',
    images: ['https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
    is_approved: true,
    metadata: { make: 'Toyota', model: 'Hilux', year: '2021', fuel: 'Diesel', listing_type: 'Sale', body_type: 'Pickup' },
    created_at: new Date(Date.now() - 43200000).toISOString(),
  },
];
